name: esm-binder
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - biopython
  - matplotlib
  - jupyter
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - huggingface_hub
      - accelerate
      - safetensors
      - esm@git+https://github.com/Biohub/esm.git@main